services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tp
      POSTGRES_USER: postgres
    volumes:
      - ./dbs/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    shm_size: 512m

  web:
    image: target:conded
    command: /bin/sh -c "chmod +x start.sh && ./start.sh"
    working_dir: /app/targetpathogenweb
    volumes:
      - ./:/app/targetpathogenweb
      - /home/gabi/tp_test/targetpathogen:/app/targetpathogen
      - /home/gabi/fasttarget/:/app/fasttarget
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - /tmp:/tmp
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DATABASE_NAME=tp
      - DJANGO_DATABASE_USER=postgres
      - DJANGO_DATABASE_PASSWORD=123
      - DJANGO_DATABASE_HOST=db
      - DJANGO_DATABASE_PORT=5432
      - POSTGRES_NAME=tp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - DJANGO_DATABASE_URL=postgres://postgres:123@db:5432/tp?sslmode=disable
      - PYTHONPATH="$${PYTHONPATH}:../sndgjobs:../sndgbiodb:../targetpathogen:../sndg-bio:../targetpathogenweb/"
      - DJANGO_DEBUG=True
      - DJANGO_SETTINGS_MODULE=tpwebconfig.settings
      - SSH_AUTH_SOCK=/ssh-agent
      - CWD=${PWD}
    depends_on:
      - db

