services:
  web:
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
    volumes:
      - ${HOME}/.ssh:/root/.ssh:ro
      - ./dummy_ssh:/ssh-agent
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
      - TPW_PROFILE=local
      - PYTHONPATH=/app/sndgjobs:/app/sndgbiodb:/app/targetpathogen:/app/sndg-bio:/app/target

  queue:
    volumes:
      - ${HOME}/.ssh:/root/.ssh:ro
      - ./dummy_ssh:/ssh-agent
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
      - TPW_PROFILE=local
      - PYTHONPATH=/app/sndgjobs:/app/sndgbiodb:/app/targetpathogen:/app/sndg-bio:/app/target
