# Generated by Django 4.2.4 on 2023-08-03 20:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
