# Generated by Django 4.2.4 on 2023-08-03 20:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0002_tppost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tppost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
