# Generated by Django 4.2.4 on 2023-08-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0003_alter_tppost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tppost',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tppost',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tppost',
            name='section',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tppost',
            unique_together={('section', 'order')},
        ),
        migrations.RemoveField(
            model_name='tppost',
            name='title',
        ),
    ]
