# Generated by Django 4.2.4 on 2023-08-22 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0008_alter_bioentry_accession_termrelationship'),
        ('tpweb', '0005_pdb_pdbresidueset_property_propertytag_residue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioentrystructure',
            name='PDB',
        ),
        migrations.AlterField(
            model_name='bioentrystructure',
            name='bioentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='bioseq.bioentry'),
        ),
        migrations.AddField(
            model_name='bioentrystructure',
            name='pdb',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='tpweb.pdb'),
            preserve_default=False,
        ),
    ]
