# Generated by Django 4.2.4 on 2023-08-31 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0009_alter_term_identifier_alter_term_name'),
        ('tpweb', '0006_remove_bioentrystructure_pdb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('C', 'CATEGORICAL'), ('N', 'NUMERIC')], max_length=255)),
                ('default_operation', models.CharField(max_length=255)),
                ('default_value', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScoreParamValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='')),
                ('numeric_value', models.FloatField(default=None, null=True)),
                ('bioentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_params', to='bioseq.bioentry')),
                ('score_param', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='tpweb.scoreparam')),
            ],
            options={
                'unique_together': {('score_param', 'bioentry')},
            },
        ),
        migrations.CreateModel(
            name='ScoreParamOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('score_param', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='tpweb.scoreparam')),
            ],
            options={
                'unique_together': {('score_param', 'name')},
            },
        ),
    ]
