# Generated by Django 4.2.4 on 2023-08-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0007_scoreparam_scoreparamvalue_scoreparamoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreparam',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='scoreparamoptions',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
    ]
