# Generated by Django 4.2.4 on 2023-08-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0008_alter_scoreparam_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreparamvalue',
            name='numeric_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
