# Generated by Django 4.2.4 on 2023-08-31 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0009_alter_scoreparamvalue_numeric_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='scoreparamoptions',
            name='score_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tpweb.scoreparam'),
        ),
        migrations.AlterField(
            model_name='scoreparamvalue',
            name='score_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpweb.scoreparam'),
        ),
        migrations.CreateModel(
            name='ScoreFormulaParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='')),
                ('operation', models.CharField(max_length=50)),
                ('coefficient', models.FloatField()),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='tpweb.scoreformula')),
                ('score_param', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpweb.scoreparam')),
            ],
            options={
                'unique_together': {('formula', 'score_param')},
            },
        ),
    ]
