# Generated by Django 4.2.4 on 2023-08-31 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0010_scoreformula_alter_scoreparamoptions_score_param_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreformula',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to=settings.AUTH_USER_MODEL),
        ),
    ]
