# Generated by Django 4.2.4 on 2023-08-31 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0012_alter_scoreformulaparam_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdbresidueset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scoreparamvalue',
            name='score_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpweb.scoreparam'),
        ),
    ]
