# Generated by Django 4.2.4 on 2023-11-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0014_userscoreformula'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreformula',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoreformula',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserScoreFormula',
        ),
    ]
