# Generated by Django 4.2.4 on 2024-04-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0015_scoreformula_default_scoreformula_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('ligand_id', models.AutoField(primary_key=True, serialize=False)),
                ('ligand_smiles', models.CharField(max_length=255)),
            ],
        ),
    ]
