# Generated by Django 4.2.4 on 2024-04-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0017_delete_ligand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('ligand_id', models.AutoField(primary_key=True, serialize=False)),
                ('ligand_from_key', models.CharField(max_length=255)),
                ('ligand_smiles', models.CharField(max_length=255)),
            ],
        ),
    ]
