# Generated by Django 4.2.4 on 2024-04-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0018_ligand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='ligand_from_key',
            field=models.CharField(default='baba', max_length=255, verbose_name='This field can represent the 3 leter pdb code or the chembl accession'),
        ),
    ]
