# Generated by Django 4.2.4 on 2024-04-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0019_alter_ligand_ligand_from_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ligand',
        ),
    ]
