# Generated by Django 4.2.4 on 2024-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0020_delete_ligand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('ligand_id', models.AutoField(primary_key=True, serialize=False)),
                ('ligand_from_key', models.CharField(default='baba', max_length=255, verbose_name='This field can represent the 3 leter pdb code or the chembl accession')),
                ('ligand_smiles', models.CharField(max_length=255)),
            ],
        ),
    ]
