# Generated by Django 4.2.4 on 2024-04-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0021_ligand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ligand',
        ),
    ]
