# Generated by Django 4.2.4 on 2024-04-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0023_ligand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='ligand_smiles',
            field=models.CharField(max_length=10000),
        ),
    ]
