# Generated by Django 4.2.4 on 2024-04-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0024_alter_ligand_ligand_smiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ligand',
        ),
    ]
