# Generated by Django 4.2.4 on 2024-04-06 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0009_alter_term_identifier_alter_term_name'),
        ('tpweb', '0026_ligand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionLigand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=255, unique=True)),
                ('bioentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioseq.bioentry', to_field='accession')),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpweb.ligand', to_field='ligand_from_key')),
            ],
        ),
    ]
