# Generated by Django 4.2.4 on 2024-04-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0027_accessionligand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessionLigand',
        ),
        migrations.DeleteModel(
            name='Ligand',
        ),
    ]
