# Generated by Django 4.2.4 on 2024-04-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0009_alter_term_identifier_alter_term_name'),
        ('tpweb', '0029_ligand_accessionligand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessionligand',
            unique_together={('locus_tag', 'ligand')},
        ),
    ]
