# Generated by Django 4.2.4 on 2024-04-26 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0009_alter_term_identifier_alter_term_name'),
        ('tpweb', '0034_alter_accessionligand_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_num', models.DecimalField(decimal_places=3, max_digits=5)),
                ('d_char', models.CharField(max_length=255)),
                ('locus_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioseq.bioentry', to_field='accession')),
            ],
        ),
    ]
