# Generated by Django 4.2.4 on 2024-04-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0035_drugindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreformulaparam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
