# Generated by Django 4.2.4 on 2024-05-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0009_alter_term_identifier_alter_term_name'),
        ('tpweb', '0036_alter_scoreformulaparam_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('path_id', models.AutoField(primary_key=True, serialize=False)),
                ('pathway', models.CharField(max_length=255)),
                ('locus_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioseq.bioentry', to_field='accession')),
            ],
            options={
                'unique_together': {('locus_tag', 'pathway')},
            },
        ),
    ]
