# Generated by Django 4.2.4 on 2024-05-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0009_alter_term_identifier_alter_term_name'),
        ('tpweb', '0037_pathway'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelularLocalization',
            fields=[
                ('ligand_id', models.AutoField(primary_key=True, serialize=False)),
                ('localization', models.CharField(max_length=255)),
                ('locus_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioseq.bioentry', to_field='accession')),
            ],
        ),
    ]
