# Generated by Django 5.0.6 on 2024-06-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0039_rename_ligand_id_celularlocalization_localization_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='residue',
            unique_together={('pdb', 'chain', 'resid', 'icode', 'type', 'resname')},
        ),
        migrations.DeleteModel(
            name='Pathway',
        ),
    ]
