# Generated by Django 4.2.13 on 2024-07-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0040_alter_residue_unique_together_delete_pathway'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=64)),
                ('tsv', models.FileField(upload_to='custom_params/')),
            ],
        ),
    ]
