# Generated by Django 4.2.4 on 2024-08-08 17:55

from django.db import migrations, models
import tpweb.models.CustomParamFile
import tpweb.storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0041_customparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customparam',
            name='tsv',
            field=models.FileField(storage=tpweb.storage.storage.OverwriteStorage(), upload_to=tpweb.models.CustomParamFile.save_location),
        ),
    ]
