# Generated by Django 4.2.4 on 2024-10-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0042_alter_customparam_tsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccd_id', models.CharField(max_length=255)),
                ('pdb_id', models.CharField(max_length=255)),
                ('uniprot', models.CharField(max_length=255)),
                ('locustag', models.CharField(max_length=255)),
                ('smiles', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='drugindex',
            name='locus_tag',
        ),
        migrations.DeleteModel(
            name='AccessionLigand',
        ),
        migrations.DeleteModel(
            name='DrugIndex',
        ),
        migrations.DeleteModel(
            name='Ligand',
        ),
    ]
