# Generated by Django 4.2.4 on 2024-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0043_binders_remove_drugindex_locus_tag_and_more'),
    ]
