# Generated by Django 4.2.4 on 2024-10-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0009_alter_term_identifier_alter_term_name'),
        ('tpweb', '0044_delete_binders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binders',
            name='locustag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioseq.bioentry', to_field='accession'),
        ),
    ]
