# Generated by Django 4.2.4 on 2024-11-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpweb', '0045_alter_binders_locustag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreformulaparam',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='scoreparamvalue',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
