#!/usr/bin/env python3
"""
Stub colabfold_batch for local development and testing.

Mimics the colabfold_batch CLI: reads input FASTA, writes a minimal
valid PDB for each sequence using the rank_001 naming convention that
colabfold_predict expects.

Usage (set in .env):
    TPW_COLABFOLD_BIN=/app/targetpathogenweb/scripts/colabfold_stub.py
"""
import os
import sys


def main():
    # colabfold_batch <input.fasta> <output_dir> [flags...]
    input_fasta = sys.argv[1]
    output_dir = sys.argv[2]

    print(f"[STUB] colabfold_batch input={input_fasta} output={output_dir}", flush=True)
    os.makedirs(output_dir, exist_ok=True)

    sequences = {}
    cur, seq = None, []
    with open(input_fasta) as f:
        for line in f:
            line = line.strip()
            if line.startswith(">"):
                if cur and seq:
                    sequences[cur] = "".join(seq)
                cur = line[1:].split()[0]
                seq = []
            else:
                seq.append(line)
    if cur and seq:
        sequences[cur] = "".join(seq)

    print(f"[STUB] Generating PDB for {len(sequences)} sequence(s)...", flush=True)

    for tag, sequence in sequences.items():
        lines = ["REMARK  Generated by colabfold_stub.py (local testing only)"]
        for i, _ in enumerate(sequence, start=1):
            lines.append(
                f"ATOM  {i:5d}  CA  ALA A{i:4d}    "
                f"   1.000   1.000   1.000  1.00  0.00           C"
            )
        lines.append("END")

        fname = f"{tag}_unrelaxed_rank_001_alphafold2_ptm_model_1_seed_000.pdb"
        with open(os.path.join(output_dir, fname), "w") as fh:
            fh.write("\n".join(lines) + "\n")
        print(f"[STUB] Wrote {fname}", flush=True)

    print("[STUB] Done.", flush=True)


if __name__ == "__main__":
    main()
