[GENERAL]
WorkingDir=/app/targetpathogenweb
Monitoring=False
MaxWorkers=1
EnvironmentFile = settings.env
[SSH]
Username=agutson
# Password intentionally blank; use SSH agent with your key
Password=
HostName = cluster.qb.fcen.uba.ar
WorkingDir=/home/agutson
Cores=4
